### ISSUE TITLE
Example of matrix testing may be wrong.

### ISSUE THREAD

**Issue by ROCKTAKEY** [conao3/setup-cask#1]
Hi, I'm glad to make such a awesome package!

On matrix testing,
```yaml
        with:
          version: '26.3'
```
should be
```yaml
        with:
          version: ${{ matrix.emacs_version }}
```
, as far as I see [Actions config for `package-lint`](https://github.com/purcell/package-lint/blob/master/.github/workflows/test.yml) referenced by [Set up Emacs](https://github.com/marketplace/actions/set-up-emacs).

Thanks!

**Comment by conao3** [comment]
Thanks for your report! I fix that.

**Comment by ROCKTAKEY** [comment]
Fixed! Thanks!
